zfcp-hbaapi,zfcp_ping: fix -Wimplicit-function-declaration
Since gcc basepoints/gcc-14 commit
https://gcc.gnu.org/git/?p=gcc.git;a=commitdiff;h=55e94561e97ed0bce4774aa1c6b5d5d82209a379
("c: Turn -Wimplicit-function-declaration into a permerror") using of
implicit declared function now triggers error instead of warning due to
-Wimplicit-function-declaration during build of the library on systems with
gcc version >= 14:

fc_tools/zfcp_ping.c:142:17: error: implicit declaration of function ‘gettimeofday’ [-Wimplicit-function-declaration]
  142 |                 gettimeofday(&start, NULL);
	  |                 ^~~~~~~~~~~~
...
vlib.c: In function 'HBA_GetAdapterAttributes':
vlib.c:647:18: error: implicit declaration of function 'sysfs_getAdapterAttributes'; did you mean 'sysfs_getAdapterPortAttributes'? [-Wimplicit-function-declaration]
  647 |         status = sysfs_getAdapterAttributes(&pAdapterattributes, adapter);
	  |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~
	  |                  sysfs_getAdapterPortAttributes
...
vlib_sg.c: In function 'sgutils_SendScsiInquiry':
vlib_sg.c:37:17: error: implicit declaration of function 'sg_cmds_open_device' [-Wimplicit-function-declaration]
   37 |         sg_fd = sg_cmds_open_device(dev_path, 0, 0);
	  |                 ^~~~~~~~~~~~~~~~~~~
vlib_sg.c:41:15: error: implicit declaration of function 'sg_ll_inquiry' [-Wimplicit-function-declaration]
   41 |         res = sg_ll_inquiry(sg_fd, 0, EVPD, PageCode, pRspBuffer,
	  |               ^~~~~~~~~~~~~
vlib_sg.c:44:17: error: implicit declaration of function 'sg_cmds_close_device' [-Wimplicit-function-declaration]
   44 |                 sg_cmds_close_device(sg_fd);
	  |                 ^~~~~~~~~~~~~~~~~~~~
vlib_sg.c: In function 'sgutils_SendReportLUNs':
vlib_sg.c:84:15: error: implicit declaration of function 'sg_ll_report_luns' [-Wimplicit-function-declaration]
   84 |         res = sg_ll_report_luns(sg_fd, 0, pRspBuffer, *RspBufferSize, 0, 0);
	  |               ^~~~~~~~~~~~~~~~~
vlib_sg.c: In function 'sgutils_SendReadCap':
vlib_sg.c:127:15: error: implicit declaration of function 'sg_ll_readcap_10' [-Wimplicit-function-declaration]
  127 |         res = sg_ll_readcap_10(sg_fd, 0, 0, pRspBuffer, READCAP10LEN, 0, 0);
	  |               ^~~~~~~~~~~~~~~~
vlib_sg.c:150:15: error: implicit declaration of function 'sg_ll_readcap_16' [-Wimplicit-function-declaration]
  150 |         res = sg_ll_readcap_16(sg_fd, 0, 0, pRspBuffer, READCAP10LEN, 0, 0);
	  |               ^~~~~~~~~~~~~~~~

Fix this by adding missing includes and by adding missing function
prototypes.

Fixes: https://github.com/ibm-s390-linux/libzfcphbaapi/issues/1
Signed-off-by: Fedor Loshakov <loshakov@linux.ibm.com>
Reviewed-by: Benjamin Block <bblock@linux.ibm.com>
Signed-off-by: Nihar Panda <niharp@linux.ibm.com>